// SystemVerilog generation. Union-find groups connected ports into nets, then
// module-kind blocks emit definitions + instantiations while primitive blocks
// emit assign/always_ff statements inside `top` via their registry emit().

import { state } from "./state.js";
import { $, esc, sanitize } from "./dom.js";
import { typeOf } from "./blockTypes.js";

function widthRange(w) { w = parseInt(w, 10); return (!w || w <= 1) ? "" : `[${w - 1}:0]`; }

function buildNets() {
  const parent = {};
  const find = (x) => { while (parent[x] !== x) { parent[x] = parent[parent[x]]; x = parent[x]; } return x; };
  const union = (a, b) => { parent[find(a)] = find(b); };
  const info = {};
  for (const b of state.blocks) for (const p of b.ports) { parent[p.id] = p.id; info[p.id] = { kind: "port", b, p }; }
  for (const t of state.tports) { parent[t.id] = t.id; info[t.id] = { kind: "tport", t }; }
  for (const w of state.wires) if (parent[w.from] !== undefined && parent[w.to] !== undefined) union(w.from, w.to);

  const groups = {};
  for (const id in parent) (groups[find(id)] ||= []).push(id);

  const netOf = {}, nets = []; let auto = 0;
  const used = new Set(state.blocks.map((b) => sanitize(b.name)).filter(Boolean));
  const widthOf = (id) => info[id].kind === "tport" ? (parseInt(info[id].t.width, 10) || 1) : (parseInt(info[id].p.width, 10) || 1);

  for (const root in groups) {
    const mem = groups[root];
    const tportMem = mem.filter((id) => info[id].kind === "tport");
    const portMem = mem.filter((id) => info[id].kind === "port");
    if (tportMem.length) {
      const t = info[tportMem[0]].t;
      let base = sanitize(t.name) || "sig", name = base, k = 1;
      while (used.has(name)) name = `${base}_${k++}`; used.add(name);
      const width = Math.max(...mem.map(widthOf));
      nets.push({ name, width, top: true, dir: t.dir, tportId: t.id });
      portMem.forEach((id) => (netOf[id] = name));
    } else if (portMem.length >= 2) {
      const drv = portMem.find((id) => info[id].p.dir === "output");
      let base = drv ? `${sanitize(info[drv].b.name) || "m"}_${sanitize(info[drv].p.name) || "o"}` : `net_${auto++}`;
      let name = base, k = 1;
      while (used.has(name)) name = `${base}_${k++}`; used.add(name);
      const width = Math.max(...portMem.map(widthOf));
      nets.push({ name, width, top: false });
      portMem.forEach((id) => (netOf[id] = name));
    }
  }
  return { netOf, nets, used };
}

export function generateSV() {
  const { netOf, nets, used } = buildNets();
  const moduleBlocks = state.blocks.filter((b) => typeOf(b).kind === "module");
  const primBlocks = state.blocks.filter((b) => typeOf(b).kind === "primitive");

  // Give every primitive port a net so emit() always references a valid name.
  // Unconnected pins become dangling internal wires (declared below).
  const extraWires = [];
  for (const b of primBlocks) for (const p of b.ports) {
    if (netOf[p.id]) continue;
    let base = `n_${sanitize(b.name) || "x"}_${sanitize(p.name) || "p"}`, name = base, k = 1;
    while (used.has(name)) name = `${base}_${k++}`; used.add(name);
    netOf[p.id] = name; extraWires.push({ name, width: parseInt(p.width, 10) || 1 });
  }
  const netName = (pid) => netOf[pid] || "";

  const tindex = {}; state.tports.forEach((t, i) => (tindex[t.id] = i));
  const topNets = nets.filter((n) => n.top).sort((a, b) => (tindex[a.tportId] ?? 1e9) - (tindex[b.tportId] ?? 1e9));
  const internalNets = nets.filter((n) => !n.top).concat(extraWires);

  const L = [];
  L.push(`// Generated by sandronelog — ${moduleBlocks.length} module(s), ${primBlocks.length} primitive(s), ${topNets.length} top-level port(s)`, "");

  // module definitions (kind: 'module')
  for (const b of moduleBlocks) {
    const name = sanitize(b.name) || "unnamed";
    L.push(`module ${name} (`);
    b.ports.forEach((p, i) => {
      const dir = (p.dir === "output" ? "output" : "input").padEnd(6), rng = widthRange(p.width), rp = rng ? rng + " " : "";
      L.push(`    ${dir} logic ${rp}${sanitize(p.name)}${i < b.ports.length - 1 ? "," : ""}`);
    });
    L.push(`);`);
    if (b.body && b.body.trim()) b.body.replace(/\r/g, "").split("\n").forEach((l) => L.push(l ? "    " + l : ""));
    L.push(`endmodule`, "");
  }

  // top-level module
  L.push(`// ---- top-level wiring ----`);
  if (topNets.length) {
    L.push(`module top (`);
    topNets.forEach((n, i) => {
      const dir = (n.dir === "output" ? "output" : "input").padEnd(6), rng = widthRange(n.width), rp = rng ? rng + " " : "";
      L.push(`    ${dir} logic ${rp}${n.name}${i < topNets.length - 1 ? "," : ""}`);
    });
    L.push(`);`);
  } else { L.push(`module top;`); }

  if (internalNets.length) { L.push(""); internalNets.forEach((n) => L.push(`    wire ${widthRange(n.width) ? widthRange(n.width) + " " : ""}${n.name};`)); }
  L.push("");

  // primitive logic (assign / always_ff)
  if (primBlocks.length) {
    primBlocks.forEach((b) => { typeOf(b).emit({ block: b, netName }).split("\n").forEach((l) => L.push(l)); });
    L.push("");
  }

  // module instantiations
  const instUsed = new Set();
  moduleBlocks.forEach((b) => {
    let inst = `u_${sanitize(b.name) || "m"}`, k = 1;
    while (instUsed.has(inst)) inst = `u_${sanitize(b.name) || "m"}_${k++}`; instUsed.add(inst);
    L.push(`    ${sanitize(b.name) || "unnamed"} ${inst} (`);
    b.ports.forEach((p, i, arr) => L.push(`        .${sanitize(p.name)} (${netName(p.id)})${i < arr.length - 1 ? "," : ""}`));
    L.push(`    );`, "");
  });
  L.push(`endmodule`);
  return L.join("\n");
}

function highlight(code) {
  return esc(code)
    .replace(/(^|\n)(\/\/.*)/g, (m, a, b) => a + `<span class="cm">${b}</span>`)
    .replace(/\b(module|endmodule|logic|wire|assign|always_ff|always_comb|posedge|negedge|if|else)\b/g, '<span class="kw">$1</span>')
    .replace(/\b(input)\b/g, '<span class="dir">$1</span>')
    .replace(/\b(output)\b/g, '<span class="out">$1</span>')
    .replace(/(\[\d+:\d+\])/g, '<span class="rng">$1</span>');
}

export function refreshSV() {
  const code = generateSV();
  $("#svOut").innerHTML = highlight(code); $("#svOut").dataset.raw = code;
  const ports = state.blocks.reduce((n, b) => n + b.ports.length, 0);
  $("#statline").innerHTML = `<span><b>${state.blocks.length}</b> blocks</span><span><b>${ports}</b> pins</span><span><b>${state.tports.length}</b> top ports</span><span><b>${state.wires.filter((w) => !w.tag).length}</b> wires</span>`;
}
